# Generated by Django 2.1.5 on 2019-01-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('data_id', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=10)),
                ('create_date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
