# Generated by Django 2.1.5 on 2019-02-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('es_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('data_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('dispatch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('file_paths', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_policies', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'relation_policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchDetailRecord',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=50, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('keyword', models.TextField(blank=True, db_column='KEYWORD', null=True)),
                ('channel', models.CharField(blank=True, db_column='CHANNEL', max_length=100, null=True)),
                ('title', models.TextField(blank=True, db_column='TITLE', null=True)),
                ('logo', models.TextField(blank=True, db_column='LOGO', null=True)),
                ('page_index', models.DecimalField(blank=True, db_column='PAGE_INDEX', decimal_places=30, max_digits=65, null=True)),
                ('page_no', models.DecimalField(blank=True, db_column='PAGE_NO', decimal_places=30, max_digits=65, null=True)),
                ('user_ip', models.CharField(blank=True, db_column='USER_IP', max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=50, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=100, null=True)),
                ('search_detail_time', models.DateTimeField(blank=True, db_column='SEARCH_DETAIL_TIME', null=True)),
                ('search_detail_stamp', models.DecimalField(blank=True, db_column='SEARCH_DETAIL_STAMP', decimal_places=30, max_digits=65, null=True)),
                ('anchor', models.CharField(blank=True, db_column='ANCHOR', max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, db_column='SOURCE_ID', max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, db_column='SESSION_ID', max_length=200, null=True)),
                ('item_unique_coding', models.CharField(blank=True, db_column='ITEM_UNIQUE_CODING', max_length=200, null=True)),
                ('user_ip_area', models.CharField(blank=True, db_column='USER_IP_AREA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SEARCH_DETAIL_RECORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=100, primary_key=True, serialize=False)),
                ('os', models.TextField(blank=True, db_column='OS', null=True)),
                ('browser', models.TextField(blank=True, db_column='BROWSER', null=True)),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=100, null=True)),
                ('remote_port', models.CharField(blank=True, db_column='REMOTE_PORT', max_length=100, null=True)),
                ('channel', models.CharField(blank=True, db_column='CHANNEL', max_length=100, null=True)),
                ('result_count', models.TextField(blank=True, db_column='RESULT_COUNT', null=True)),
                ('session_id', models.TextField(blank=True, db_column='SESSION_ID', null=True)),
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=100, null=True)),
                ('search_date', models.CharField(blank=True, db_column='SEARCH_DATE', max_length=100, null=True)),
                ('search_time', models.CharField(blank=True, db_column='SEARCH_TIME', max_length=100, null=True)),
                ('extend_1', models.TextField(blank=True, db_column='EXTEND_1', null=True)),
                ('extend_2', models.TextField(blank=True, db_column='EXTEND_2', null=True)),
                ('extend_3', models.TextField(blank=True, db_column='EXTEND_3', null=True)),
                ('keyword', models.TextField(blank=True, db_column='KEYWORD', null=True)),
                ('query_time', models.TextField(blank=True, db_column='QUERY_TIME', null=True)),
                ('ip_area', models.CharField(blank=True, db_column='IP_AREA', max_length=255, null=True)),
                ('ip_num', models.TextField(blank=True, db_column='IP_NUM', null=True)),
            ],
            options={
                'db_table': 'SEARCH_RECORD',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PolicyInfo',
        ),
    ]
